# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BrewTest < Formula
  desc ""
  homepage "https://github.com/nadav-legit/brew_test"
  version "0.0.7"

  on_macos do
    url "https://github.com/nadav-legit/brew_test/releases/download/0.0.7/brew_test_0.0.7_darwin_all.tar.gz"
    sha256 "d33c0523a23d3b66e62ad7c236d8bcc33b98b06914b48d3736ec045980db92e8"

    def install
      bin.install "brew_test"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nadav-legit/brew_test/releases/download/0.0.7/brew_test_0.0.7_linux_arm64.tar.gz"
      sha256 "cb9a8c90c85c1e737028b9f8380b31124a25327d76a70ce5c43fb264bb130e61"

      def install
        bin.install "brew_test"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nadav-legit/brew_test/releases/download/0.0.7/brew_test_0.0.7_linux_amd64.tar.gz"
      sha256 "a982399ab0dfaab42642e0c080f7a28d01fe0f6df5ebb1862135fec7109c2571"

      def install
        bin.install "brew_test"
      end
    end
  end
end
