# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mediumautopost < Formula
  desc ""
  homepage "https://github.com/nadav-legit/brew_test"
  version "0.0.4"

  on_macos do
    url "https://github.com/nadav-legit/brew_test/releases/download/0.0.4/brew_test_0.0.4_darwin_all.tar.gz"
    sha256 "0722a649387f3475d10f9e01254b42e5a4d059377849b025c0aac367692d50fb"

    def install
      bin.install "brew_test"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/nadav-legit/brew_test/releases/download/0.0.4/brew_test_0.0.4_linux_amd64.tar.gz"
      sha256 "f91a073a52a1d8a2b4e6272a055a564ef15d4ae722bb7eda39d32c61d49f3f87"

      def install
        bin.install "mediumautopost"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nadav-legit/brew_test/releases/download/0.0.4/brew_test_0.0.4_linux_arm64.tar.gz"
      sha256 "bb740de01965198a6701947c8609baa3da8a2289087b8a763baf8ad2a7de6292"

      def install
        bin.install "mediumautopost"
      end
    end
  end
end
