# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NadavFirstBrew < Formula
  desc ""
  homepage "https://github.com/nadav-legit/brew_test"
  version "0.0.5"

  on_macos do
    url "https://github.com/nadav-legit/brew_test/releases/download/0.0.5/brew_test_0.0.5_darwin_all.tar.gz"
    sha256 "49826e330d0d21c6a09c37e5e6c7a11332629dc6bbfe9cc2244781095f28ce75"

    def install
      bin.install "brew_test"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nadav-legit/brew_test/releases/download/0.0.5/brew_test_0.0.5_linux_arm64.tar.gz"
      sha256 "2d3d63fbf28e2efe7f9c280025cda60e1dd7f8bbf4f1d78496927acfcd1717c8"

      def install
        bin.install "mediumautopost"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nadav-legit/brew_test/releases/download/0.0.5/brew_test_0.0.5_linux_amd64.tar.gz"
      sha256 "5331b73b82b8fafd9e17a256dad6e28118a91667d5c2aba902f4aed2b183664f"

      def install
        bin.install "mediumautopost"
      end
    end
  end
end
