# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NadavFirstBrew < Formula
  desc ""
  homepage "https://github.com/nadav-legit/brew_test"
  version "0.0.6"

  on_macos do
    url "https://github.com/nadav-legit/brew_test/releases/download/0.0.6/brew_test_0.0.6_darwin_all.tar.gz"
    sha256 "b0121fb6ea762c3643655b29d6df671cfad04dc0b00d1fb787b39974715e8bbf"

    def install
      bin.install "brew_test"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nadav-legit/brew_test/releases/download/0.0.6/brew_test_0.0.6_linux_arm64.tar.gz"
      sha256 "e6599da83d9b9abedd61a4b83dcd181fdca7e7ca4ecf7b581578e8212f705d7f"

      def install
        bin.install "nadav_first_brew"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/nadav-legit/brew_test/releases/download/0.0.6/brew_test_0.0.6_linux_amd64.tar.gz"
      sha256 "2ca7843e0b242e6eaf675aaf37ff8298528878d4058369400df87e67675158db"

      def install
        bin.install "nadav_first_brew"
      end
    end
  end
end
